
# To connect mysqlserver we need some libraires in python
- name: Install mysql libraries
  ansible.builtin.pip:
    name: "{{ item}}"
    executable: pip3.9
  loop:
  - cryptography
  - pymysql
- name: installing mysql server
  ansible.builtin.pasckage:
    name: mysql-server
    state: installed
- name: start and enable mysql server
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
# to connect database is connected or not
- name: connect to mysql server
  commmunity.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_password}}"
    login_host: mysql.daws82s.online #ip addres or route53record name
    # to take the output we will use register variable in ansible to store the output
    register: mysql_info
    ignore_errors: true
  # if we got any error it will skip that error

- name: print the output
  ansible.builtin.debug:
    msg: "mysql info: {{ mysql_info }}"

- name: setup root password
  ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_password }} "
  when: mysql_info.failed is true
