- name: remove existing directory
  ansible.builtin.file:
    path: "{{  APP_LOCATION }}" # backend folder is /app and fronend is /usr/share/nginx/html
    state: absent

- name: remove existing directory
  ansible.builtin.file:
    path: "{{  APP_LOCATION }}" # backend folder is /app and fronend is /usr/share/nginx/html
    state: directory

- name: download the application code
  ansible.builtin.unarchive: # we will use unarchive module it will automatically download and extract the file
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}"
    remote_src: yes

